---
#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------


# Set Var for curent DO file name
  - name: Retrieve DO Install Version
    find:
      paths: ./files
      patterns: "f5-decl*.rpm"
    register: dorpm
    delegate_to: localhost


  - name: Install DO
    bigip_iapplx_package:
      provider: "{{ hostvars[inventory_hostname]['provider']  }}"
      server: localhost
      user: admin
      password: "{{ vault_password }}"
      validate_certs: no
      server_port: 443
      package: "{{ dorpm.files[0].path }}"
    delegate_to: localhost


  - name: Push DO
    uri:
      url: "https://{{ hostvars[inventory_hostname]['provider']['server'] }}:{{ hostvars[inventory_hostname]['provider']['server_port'] }}/mgmt/shared/declarative-onboarding"
      method: POST
      user: admin
      password: "{{ hostvars[inventory_hostname]['provider']['password'] }}"
      body: "{{ lookup('file','host_vars/' + inventory_hostname + '/do.json') }}"
      status_code: 202
      timeout: 300
      body_format: json
      validate_certs: no
    delegate_to: localhost

#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...