---
#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------


# Set Var for curent DO file name
  - name: Retrieve DO Install Version
    find:
      paths: ../files
      patterns: "f5-decl*.rpm"
    register: dorpm
    delegate_to: localhost


  - name: Install DO
    bigip_iapplx_package:
      provider: "{{ provider }}"
      package: "{{ dorpm.files[0].path }}"
    delegate_to: localhost


  - name: WAIT FOR DO API READY
    uri:
      url: "https://{{ net_mgmt.ip }}:{{ provider.server_port }}/mgmt/shared/declarative-onboarding"
      method: GET
      user: admin
      password: "{{ provider.password }}"
      status_code: 401 
      validate_certs: no
    retries: 30
    delay: 5
    register: do_result
    until: ('status' in do_result) and (do_result.status == 401)
    changed_when: false

  - name: Push DO
    uri:
      url: "https://{{ net_mgmt.ip }}:{{ provider.server_port }}/mgmt/shared/declarative-onboarding"
      method: POST
      user: admin
      password: "{{ provider.password }}"
      body: "{{ lookup('template', '../declarations/do.j2', split_lines=False) }}"
      status_code: 202
      timeout: 300
      body_format: json
      validate_certs: no
    delegate_to: localhost

#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...