---
#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------


# Set Var for curent AS3 file name
  - name: RETRIEVE AS3 VERSION FROM FILE
    find:
      paths: ../files
      patterns: "f5-appsvcs*.rpm"
    register: as3rpm
    delegate_to: localhost


  - name: INSTALL AS3
    bigip_iapplx_package:
      provider: "{{ provider }}"
      package: "{{ as3rpm.files[0].path }}"
    delegate_to: localhost


  - name: WAIT FOR AS3 API (204)
    uri:
      url: "https://{{ net_mgmt.ip }}:{{ provider.server_port }}/mgmt/shared/appsvcs/declare"
      method: GET
      user: admin
      password: "{{ provider.password }}"
      force_basic_auth: yes
      status_code: 204 
      validate_certs: no
    retries: 30
    delay: 5
    register: as3_result
    until: ('status' in as3_result) and (as3_result.status == 204)
    changed_when: false


  - name: AS3 REST CALL TO BIG-IP USING JINJA2 TEMPLATE
    uri:
      url: "https://{{ net_mgmt.ip }}:{{ provider.server_port }}/mgmt/shared/appsvcs/declare"
      method: POST
      force_basic_auth: yes
      user: admin
      password: "{{ provider.password }}"
      body: "{{ lookup('template', '../declarations/as3-declaration.j2', split_lines=False) }}"
      body_format: json
      status_code: 200
      timeout: 120
      validate_certs: no
    register: deploy_as3
    until: deploy_as3 is not failed
    retries: 5
    delay: 30

#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...