---
#------------------------------------------------------------------------------
# Ansible Playbook to Delete Demo Environment
#------------------------------------------------------------------------------

- name: DELETE BIGIPS FROM VMWARE
  hosts: lbaas
  connection: local
  gather_facts: no


#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------
  
  # You need to create a file named aws_creds.yaml (update path below) with the following variables:
  #
  #  ec2_access_key: "--your-key-here--"
  #  ec2_secret_key: "--your-secret-here--"
  #
  vars_files:
  - ../vars/bigip_creds.yaml
  - ../vars/vmware_creds.yaml
  - ../vars/vmware_vars.yaml

  
#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Start Tasks
#------------------------------------------------------------------------------

  tasks:

  - include_tasks: ../tasks/tasks-11-delete-vmware-vm.yaml


#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...