---
#------------------------------------------------------------------------------
# Playbook to CREATE VMWare demo environment. 
#
#   Requires pyvmomi python librarypy
#------------------------------------------------------------------------------

- name: PREP VMWARE OVA FILE - ONE TIME TASK
  hosts: localhost
  connection: local
  gather_facts: no


#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------
  
  vars_files:

    - ../vars/vmware_vars.yaml
   
#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------
  
  tasks:

  - name: ADD CUSTOM GUEST PROPERTIES TO VMWARE OVA FILE
    command: "{{ lookup('template', '../declarations/cot-template.bash.j2', split_lines=False) }}"
    
#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...